# Generated by Django 4.0.4 on 2022-05-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='level',
            field=models.IntegerField(default=1, help_text='Total level'),
        ),
        migrations.AddField(
            model_name='character',
            name='pp',
            field=models.IntegerField(help_text='Passive perception', null=True, verbose_name='PP'),
        ),
    ]
