# Generated by Django 4.0.4 on 2022-05-14 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('codex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='downtime',
            field=models.FloatField(blank=True, help_text='Days of downtime', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='content_type',
            field=models.ForeignKey(help_text='Type of event that resulted in this object coming to you', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Origin Type'),
        ),
        migrations.AlterField(
            model_name='item',
            name='object_id',
            field=models.PositiveIntegerField(help_text='ID of the specific source event', null=True, verbose_name='Event ID'),
        ),
    ]
