# Generated by Django 4.0.4 on 2022-05-13 20:54

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codexuser',
            options={'verbose_name': 'Codex User'},
        ),
        migrations.AlterField(
            model_name='codexuser',
            name='discord_id',
            field=models.CharField(blank=True, help_text='Discord ID for bot integration', max_length=32, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='codexuser',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper('username'), name='username_unique'),
        ),
        migrations.AddConstraint(
            model_name='codexuser',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper('email'), name='email_unique'),
        ),
        migrations.AddConstraint(
            model_name='codexuser',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper('discord_id'), name='discord_id_unique'),
        ),
    ]
