# Generated by Django 4.0.4 on 2022-05-13 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0002_alter_codexuser_options_alter_codexuser_discord_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codexuser',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='User has verified their email address'),
        ),
    ]
