# Generated by Django 4.0.4 on 2022-05-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0002_character_level_character_pp'),
    ]

    operations = [
        migrations.AddField(
            model_name='magicitem',
            name='attunement',
            field=models.BooleanField(default=False, help_text='Item requires attunement to be used'),
        ),
        migrations.AddField(
            model_name='magicitem',
            name='equipped',
            field=models.BooleanField(default=False, help_text='Item is currently equipped by its owner'),
        ),
    ]
