# Generated by Django 4.0.4 on 2022-06-04 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0002_alter_game_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmreward',
            name='dm',
            field=models.ForeignKey(help_text='Moonsea Codex DM', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='codex.dungeonmasterinfo'),
        ),
    ]
