# Generated by Django 4.0.4 on 2022-05-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0003_codexuser_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='ac',
            field=models.IntegerField(help_text='Base armour class', null=True, verbose_name='AC'),
        ),
        migrations.AlterField(
            model_name='character',
            name='dc',
            field=models.IntegerField(help_text='Spell Save DC', null=True, verbose_name='DC'),
        ),
        migrations.AlterField(
            model_name='character',
            name='hp',
            field=models.IntegerField(help_text='Max HP', null=True, verbose_name='HP'),
        ),
        migrations.AlterField(
            model_name='character',
            name='portrait',
            field=models.ImageField(blank=True, null=True, upload_to='artwork'),
        ),
        migrations.AlterField(
            model_name='character',
            name='token',
            field=models.ImageField(blank=True, null=True, upload_to='tokens'),
        ),
        migrations.AlterField(
            model_name='character',
            name='vision',
            field=models.CharField(blank=True, help_text='Any special vision modes (eg darkvision)', max_length=64, null=True),
        ),
    ]
