# Generated by Django 4.0.4 on 2022-06-04 17:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0003_alter_dmreward_dm'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
