# Generated by Django 4.0.4 on 2022-07-01 12:30

import codex.models.api_keys
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0003_consumable_uuid_magicitem_uuid_alter_character_gold_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(help_text='Key name', max_length=128)),
                ('description', models.TextField(blank=True, help_text='Description of the key usage', null=True)),
                ('value', models.CharField(default=codex.models.api_keys.generate_random_key, help_text='Key value', max_length=64)),
                ('datetime', models.DateTimeField(auto_now_add=True, help_text='When the key was created')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API key',
                'verbose_name_plural': 'API keys',
            },
        ),
    ]
