# Generated by Django 4.0.4 on 2022-08-18 20:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0004_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
