# Generated by Django 4.0.4 on 2022-05-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0004_remove_character_portrait_character_artwork_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='artwork',
        ),
        migrations.AddField(
            model_name='character',
            name='portrait',
            field=models.ImageField(blank=True, null=True, upload_to='artwork'),
        ),
        migrations.AlterField(
            model_name='character',
            name='token',
            field=models.ImageField(blank=True, null=True, upload_to='tokens'),
        ),
    ]
