# Generated by Django 4.0.4 on 2022-05-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0005_remove_character_artwork_character_portrait_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='portrait',
            field=models.ImageField(blank=True, null=True, upload_to='character/artwork'),
        ),
        migrations.AlterField(
            model_name='character',
            name='token',
            field=models.ImageField(blank=True, null=True, upload_to='character/tokens'),
        ),
    ]
