# Generated by Django 4.0.4 on 2022-06-19 11:08

import codex.models.character
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0005_rename_portrait_character_artwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='artwork',
            field=models.ImageField(blank=True, null=True, upload_to=codex.models.character.get_user_artwork_path),
        ),
        migrations.AlterField(
            model_name='character',
            name='token',
            field=models.ImageField(blank=True, null=True, upload_to=codex.models.character.get_user_token_path),
        ),
    ]
