# Generated by Django 4.0.4 on 2022-08-19 19:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0006_alter_trade_associated'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(blank=True, default='Created by user', help_text='Type of manual creation', max_length=32, null=True)),
                ('character', models.ForeignKey(blank=True, help_text='Character item was created for', null=True, on_delete=django.db.models.deletion.SET_NULL, to='codex.character')),
            ],
        ),
    ]
