# Generated by Django 4.0.4 on 2022-05-28 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0006_alter_character_portrait_alter_character_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='DungeonMasterLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.IntegerField(blank=True, help_text='Total number of DMing service hours unspent')),
                ('player', models.ForeignKey(help_text='The player this DM log belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='dm_log', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
