# Generated by Django 4.0.4 on 2022-08-20 22:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0007_manualcreation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(blank=True, default='Item name changed', help_text='Type of edit undertaken', max_length=64, null=True)),
                ('details', models.CharField(blank=True, help_text='Information about the edit operation', max_length=256, null=True)),
                ('character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='codex.character')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='codex.magicitem')),
            ],
        ),
    ]
