# Generated by Django 4.0.4 on 2022-05-29 09:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0007_dungeonmasterlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='dungeonmasterlog',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='dungeonmasterlog',
            name='hours',
            field=models.IntegerField(blank=True, default=0, help_text='Total number of DMing service hours unspent'),
        ),
    ]
