# Generated by Django 4.0.4 on 2022-08-31 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0008_manualedit'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='init',
            field=models.IntegerField(help_text='Character initiative modifier', null=True, verbose_name='Initiative'),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(default='Unnamed character', max_length=256),
        ),
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='season',
            field=models.CharField(blank=True, default='11', help_text='AL season that this character was created', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='vision',
            field=models.CharField(blank=True, help_text='Any special vision modes (eg darkvision)', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='codexuser',
            name='discord_id',
            field=models.CharField(blank=True, help_text='Discord ID for bot integration', max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='name',
            field=models.CharField(help_text='Item Name', max_length=256),
        ),
        migrations.AlterField(
            model_name='dmreward',
            name='name',
            field=models.CharField(blank=True, help_text='Service reward name', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='dm_name',
            field=models.CharField(default='', help_text='Name of DM', max_length=128),
        ),
        migrations.AlterField(
            model_name='game',
            name='hours_notes',
            field=models.TextField(blank=True, help_text='Time breakdown for game', null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='location',
            field=models.CharField(blank=True, help_text='Where the game was organised or run', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='module',
            field=models.CharField(help_text='Module code', max_length=128),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(blank=True, help_text='Module name', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='notes',
            field=models.TextField(blank=True, help_text='Public DM notes for game', null=True),
        ),
        migrations.AlterField(
            model_name='magicitem',
            name='name',
            field=models.CharField(help_text='Item Name', max_length=256),
        ),
        migrations.AlterField(
            model_name='manualcreation',
            name='name',
            field=models.CharField(blank=True, default='Created by user', help_text='Type of manual creation', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='manualedit',
            name='name',
            field=models.CharField(blank=True, default='Item name changed', help_text='Type of edit undertaken', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='recipient_name',
            field=models.CharField(blank=True, help_text='Optional character name', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='sender_name',
            field=models.CharField(blank=True, help_text='Optional character name', max_length=128, null=True),
        ),
    ]
