# Generated by Django 4.0.4 on 2022-08-31 19:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0009_character_init_alter_character_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('description', models.TextField(blank=True, help_text='Text to display on the item offered', null=True)),
            ],
            options={
                'verbose_name': 'Trade advert',
            },
        ),
        migrations.AddField(
            model_name='magicitem',
            name='tradable',
            field=models.BooleanField(default=False, help_text='Item is in trading post'),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('description', models.TextField(blank=True, help_text='Text to display on the items offered', null=True)),
                ('advert', models.ForeignKey(help_text='Item that proposal is for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='codex.advert')),
                ('item', models.ForeignKey(help_text='Item offered in trade', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_offers', to='codex.magicitem')),
            ],
            options={
                'verbose_name': 'Trade offer',
            },
        ),
        migrations.AddField(
            model_name='advert',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adverts', to='codex.magicitem'),
        ),
    ]
