# Generated by Django 4.0.4 on 2022-09-01 15:16

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0010_advert_magicitem_tradable_offer_advert_item'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='advert',
            index=models.Index(fields=['uuid'], name='advert_uuid_idx'),
        ),
        migrations.AddIndex(
            model_name='advert',
            index=models.Index(fields=['item'], name='advert_item_idx'),
        ),
        migrations.AddIndex(
            model_name='magicitem',
            index=models.Index(fields=['uuid'], name='item_uuid_idx'),
        ),
        migrations.AddIndex(
            model_name='magicitem',
            index=models.Index(fields=['character'], name='item_character_idx'),
        ),
        migrations.AddIndex(
            model_name='magicitem',
            index=models.Index(fields=['name'], name='item_name_idx'),
        ),
        migrations.AddIndex(
            model_name='magicitem',
            index=models.Index(django.db.models.functions.text.Upper('name'), name='item_name_upper_idx'),
        ),
        migrations.AddIndex(
            model_name='magicitem',
            index=models.Index(fields=['tradable'], name='item_tradable_idx'),
        ),
        migrations.AddIndex(
            model_name='magicitem',
            index=models.Index(fields=['content_type', 'object_id'], name='item_source_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['uuid'], name='offer_uuid_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['advert'], name='offer_advert_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['item'], name='offer_item_idx'),
        ),
    ]
