# Generated by Django 4.0.4 on 2022-09-18 20:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0013_codexuser_user_email_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatchingUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('levels', models.IntegerField(default=1)),
                ('details', models.CharField(blank=True, help_text='Optional further details', max_length=256, null=True)),
                ('character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='codex.character')),
            ],
        ),
        migrations.AddIndex(
            model_name='catchingup',
            index=models.Index(fields=['uuid'], name='event_catchup_uuid_idx'),
        ),
        migrations.AddIndex(
            model_name='catchingup',
            index=models.Index(fields=['character'], name='event_catchup_character_idx'),
        ),
    ]
