# Generated by Django 4.0.4 on 2022-09-19 19:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0014_catchingup_catchingup_event_catchup_uuid_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MundaneTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('gold_change', models.FloatField(default=0, help_text='Gold change from this trade')),
                ('sold', models.TextField(blank=True, help_text='Items sold', null=True)),
                ('purchased', models.TextField(blank=True, help_text='Items purchased', null=True)),
                ('character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='codex.character')),
            ],
        ),
        migrations.AddIndex(
            model_name='mundanetrade',
            index=models.Index(fields=['uuid'], name='event_mtrade_uuid_idx'),
        ),
        migrations.AddIndex(
            model_name='mundanetrade',
            index=models.Index(fields=['character'], name='event_mtrade_character_idx'),
        ),
    ]
