# Generated by Django 4.0.4 on 2024-07-03 20:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0015_mundanetrade_mundanetrade_event_mtrade_uuid_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpellbookUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('gold', models.FloatField(default=0, help_text='Gold spent on reagents')),
                ('downtime', models.FloatField(default=0, help_text='Downtime days spent copying')),
                ('dm', models.CharField(blank=True, help_text='DM associated with update event', max_length=128, null=True)),
                ('spells', models.TextField(blank=True, help_text='Spells added to spellbook', null=True)),
                ('character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='codex.character')),
            ],
        ),
        migrations.AddIndex(
            model_name='spellbookupdate',
            index=models.Index(fields=['uuid'], name='event_sbookupd_uuid_idx'),
        ),
        migrations.AddIndex(
            model_name='spellbookupdate',
            index=models.Index(fields=['character'], name='event_sbookupd_character_idx'),
        ),
    ]
