# Generated by Django 5.0.6 on 2024-07-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codex", "0016_spellbookupdate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="spellbookupdate",
            name="source",
            field=models.CharField(
                blank=True,
                help_text="Source character for spells",
                max_length=128,
                null=True,
            ),
        ),
    ]
