# Generated by Django 5.1.1 on 2025-01-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0018_remove_consumable_content_type_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='magicitem',
            name='item_tradable_idx',
        ),
        migrations.RenameField(
            model_name='magicitem',
            old_name='tradable',
            new_name='market',
        ),
        migrations.AddIndex(
            model_name='magicitem',
            index=models.Index(fields=['market'], name='item_tradable_idx'),
        ),
    ]
