# Generated by Django 5.0.6 on 2025-01-10 21:18

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codex", "0018_remove_consumable_content_type_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="magicitem",
            name="item_tradable_idx",
        ),
        migrations.RenameField(
            model_name="magicitem",
            old_name="tradable",
            new_name="market",
        ),
        migrations.AddField(
            model_name="magicitem",
            name="minor_properties",
            field=models.TextField(
                blank=True, help_text="Minor properties - guardian, etc", null=True
            ),
        ),
        migrations.AddField(
            model_name="magicitem",
            name="rp_name",
            field=models.TextField(blank=True, help_text="Roleplay name", null=True),
        ),
        migrations.AddField(
            model_name="magicitem",
            name="url",
            field=models.URLField(
                blank=True, help_text="Link to item details", null=True
            ),
        ),
        migrations.AlterField(
            model_name="magicitem",
            name="name",
            field=models.CharField(help_text="Base item name", max_length=256),
        ),
        migrations.AddIndex(
            model_name="magicitem",
            index=models.Index(fields=["rp_name"], name="item_rp_name_idx"),
        ),
        migrations.AddIndex(
            model_name="magicitem",
            index=models.Index(
                django.db.models.functions.text.Upper("rp_name"),
                name="item_rp_name_upper_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="magicitem",
            index=models.Index(fields=["market"], name="item_tradable_idx"),
        ),
    ]
