# Generated by Django 5.1.6 on 2025-03-08 14:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codex", "0021_game_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="FreeForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "datetime",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("title", models.CharField(default="Freeform event", max_length=256)),
                (
                    "details",
                    models.TextField(
                        blank=True, help_text="Optional further details", null=True
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="codex.character",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["uuid"], name="event_freeform_uuid_idx"),
                    models.Index(
                        fields=["character"], name="event_freeform_character_idx"
                    ),
                ],
            },
        ),
    ]
