# Generated by Django 5.1.6 on 2025-03-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codex", "0022_freeform"),
    ]

    operations = [
        migrations.AddField(
            model_name="freeform",
            name="downtime_change",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="Downtime change for this event, negative values indicate downtime used",
            ),
        ),
        migrations.AddField(
            model_name="freeform",
            name="gold_change",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="Gold change for this event, negative values indicate gold spent",
            ),
        ),
    ]
