# Generated by Django 5.1.6 on 2025-04-17 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("codex", "0023_freeform_downtime_change_freeform_gold_change"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mundanetrade",
            name="character",
        ),
        migrations.DeleteModel(
            name="CatchingUp",
        ),
        migrations.DeleteModel(
            name="MundaneTrade",
        ),
    ]
