# Generated by Django 5.1.7 on 2025-05-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codex", "0026_consumable_content_type_consumable_object_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="bastion",
            field=models.CharField(
                blank=True, help_text="Link to bastion map", max_length=256, null=True
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="campaign",
            field=models.CharField(
                blank=True, default="Forgotten Realms", max_length=128, null=True
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="faction",
            field=models.CharField(
                blank=True,
                help_text="Faction and reknown level",
                max_length=128,
                null=True,
            ),
        ),
    ]
