# Generated by Django 5.1.7 on 2025-05-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codex", "0027_character_bastion_character_campaign_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="bastion",
            field=models.CharField(
                blank=True, default="", help_text="Link to bastion map", max_length=256
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="campaign",
            field=models.CharField(
                blank=True, default="Forgotten Realms", max_length=128
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="faction",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Faction and reknown level",
                max_length=128,
            ),
        ),
    ]
